import { riskColor } from './RiskBadge.jsx'

/**
 * Renders the §24 bullet-point reason plus the weighted contribution chart.
 *
 * The text comes from the backend, which builds it by substituting the stored
 * RiskAssessment numbers into fixed templates. Nothing here is generated by a
 * language model — that is the point: a judge asking "how did you write that
 * sentence?" gets a straight answer.
 */

/**
 * Points contributed, drawn to scale.
 *
 * This used to be a bar chart of each component's RAW 0-100 score, with the
 * weight and the points hidden in a tooltip. That made a maxed-out ETA margin
 * (weight 0.10) look as important as a maxed-out temperature (weight 0.25).
 * Now each component's track is as long as the most it can ever contribute
 * (weight x 100), and the fill is what it contributes right now - so the eye
 * reads both the weight and the score, and the labels state the points.
 * One colour: these are one measure, and the ranking does the talking.
 */
function ContributionBars({ contributions }) {
  const rows = [...contributions].sort((a, b) => b.points - a.points)
  const scaleMax = Math.max(...rows.map((c) => c.weight * 100), 1)
  return (
    <ul className="space-y-2">
      {rows.map((c) => {
        const cap = c.weight * 100
        return (
          <li key={c.component} className="grid grid-cols-[92px_1fr_auto] items-center gap-3 text-xs">
            <span className="truncate text-ink-2">{c.component}</span>
            <span className="relative h-3.5 rounded-sm" aria-hidden="true">
              <span
                className="absolute inset-y-0 left-0 rounded-sm bg-surface-sunken ring-1 ring-inset ring-line"
                style={{ width: `${(cap / scaleMax) * 100}%` }}
              />
              <span
                className="absolute inset-y-0 left-0 rounded-sm bg-series-1"
                style={{ width: `${(c.points / scaleMax) * 100}%` }}
              />
            </span>
            <span className="num whitespace-nowrap text-right text-ink-2">
              <span className="font-semibold text-ink-1">+{c.points.toFixed(1)}</span>
              <span className="text-ink-3"> / {cap.toFixed(0)} pts</span>
            </span>
          </li>
        )
      })}
    </ul>
  )
}

export default function ExplainabilityPanel({ explanation, showChart = true }) {
  if (!explanation) {
    return <p className="text-sm text-ink-3">No assessment recorded yet.</p>
  }

  const contributions = explanation.contributions ?? []
  const total = contributions.reduce((sum, c) => sum + c.points, 0)

  return (
    <div className="space-y-4">
      <div>
        <p className="font-semibold text-ink-1">{explanation.headline}</p>
        <ul className="mt-2 space-y-1.5">
          {explanation.bullets.map((bullet, index) => (
            <li key={index} className="flex gap-2 text-sm text-ink-2">
              <span
                className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full"
                style={{ backgroundColor: riskColor(explanation.status) }}
                aria-hidden="true"
              />
              <span>{bullet}</span>
            </li>
          ))}
        </ul>
      </div>

      {showChart && contributions.length > 0 && (
        <div>
          <p className="card-title mb-2">
            Weighted contribution to the score ({total.toFixed(1)} of 100 points)
          </p>
          <ContributionBars contributions={contributions} />
          <p className="mt-1 text-[11px] leading-relaxed text-ink-3">
            Each track is the most that component can contribute (its weight × 100); the fill is
            what it contributes now. {explanation.disclaimer}
          </p>
        </div>
      )}
    </div>
  )
}
