"""Where every number on the dashboard actually comes from.

Four labels, used consistently and never interchangeably:

  LIVE       a real external service answered this request
  USER       data the operator owns and supplied (reserved; unused so far)
  SIMULATED  generated by this application's own models
  PREDICTED  computed by a formula or a trained model from the two above

The point is not decoration. A cold-chain dashboard that shows a simulated
sensor trace next to a real weather reading, with no visual difference between
them, is making a claim it cannot support.

The stream CATALOGUE now lives in `app/providers/registry.py`, next to the
chains that fetch each one, so a row cannot drift away from the code that
feeds it. What is left here is the part that is only knowable at runtime: which
provider actually answered, and whether a scenario has perturbed the values
since they were stored.
"""

from __future__ import annotations

from datetime import datetime, timezone

from sqlalchemy.orm import Session

from app.config import settings
from app.ml.registry import model_status
from app.providers import registry
from app.providers.base import (
    LIVE,
    MIXED,
    PREDICTED,
    SIMULATED,
    USER,
    combined_label,
    label_for_source,
)
from app.services import weather

__all__ = ["LIVE", "USER", "SIMULATED", "PREDICTED", "MIXED", "weather_summary", "streams", "summary"]


def _utc_iso(value: datetime | None) -> str | None:
    """Real observation time with an explicit UTC offset (SQLite returns naive UTC)."""
    if value is None:
        return None
    return (value if value.tzinfo else value.replace(tzinfo=timezone.utc)).isoformat()


def weather_summary(db: Session) -> dict:
    """Per-waypoint provenance for the weather feed.

    Note the `ambient_offset_c` handling. A scenario injection is applied when
    a lane's ambient is READ, not when the observation is stored, so the stored
    rows stay genuinely live while the temperature the thermal model sees is
    not. Reporting LIVE in that state would be the exact false claim this
    module exists to prevent, so an active offset downgrades the label to
    MIXED and says by how much.
    """
    from app.simulation import physics

    observations = weather.latest_all(db)
    # Counted by LABEL, not by one specific source string: the moment a second
    # live provider exists, "is this live" stops being "did Open-Meteo answer".
    live = [o for o in observations if label_for_source(o.source) == LIVE]
    stored_injected = [o for o in observations if o.source == weather.INJECTED]
    offset = float(physics.environment(db).ambient_offset_c)

    # An injection overrides the unanimous verdict: every stored row can be
    # honestly LIVE while the number the thermal model reads is not one of them.
    label = MIXED if offset > 0 else combined_label([o.source for o in observations])

    return {
        "label": label,
        "ambient_offset_c": round(offset, 2),
        "offset_active": offset > 0,
        "provider": "Open-Meteo" if live else "internal diurnal model",
        "enabled": settings.weather_enabled,
        "waypoints_total": len(observations),
        "waypoints_live": len(live),
        "waypoints_injected": len(stored_injected),
        "observations": [
            {
                "city": o.city,
                "temperature_c": o.temperature_c,
                "humidity_pct": o.humidity_pct,
                "precipitation_mm": o.precipitation_mm,
                "wind_kph": o.wind_kph,
                "weather_level": o.weather_level,
                "condition": o.condition,
                "source": o.source,
                # Derived from the persisted source, never stored alongside it -
                # two columns that can disagree is how a simulated reading ends
                # up wearing a LIVE chip.
                "label": label_for_source(o.source),
                "observed_at": _utc_iso(o.observed_at),
            }
            for o in sorted(observations, key=lambda o: o.city)
        ],
    }


def _weather_detail(w: dict) -> str:
    if w["offset_active"]:
        base = (
            f"Open-Meteo, {w['waypoints_live']}/{w['waypoints_total']} waypoints live"
            if w["waypoints_live"]
            else "simulated diurnal curve"
        )
        return (
            f"{base}, but a scenario is adding +{w['ambient_offset_c']} C to ambient - "
            "the temperature driving the thermal model is NOT the observed one."
        )
    if w["waypoints_live"]:
        return f"Open-Meteo, {w['waypoints_live']}/{w['waypoints_total']} waypoints live"
    return "Open-Meteo unreachable - simulated diurnal curve"


def _model_detail() -> str:
    loaded = [
        name.removesuffix(".joblib")
        for name, status in model_status().items()
        if status.get("loaded")
    ]
    return (
        "scikit-learn models loaded: "
        f"{', '.join(loaded) if loaded else 'none - using rule-based fallbacks'}."
    )


def streams(db: Session) -> list[dict]:
    """One row per data stream, for the provenance strip in the header.

    Everything static comes from the registry; only the two rows whose answer
    depends on what happened at runtime are overridden.
    """
    w = weather_summary(db)
    return registry.rows(
        overrides={
            "weather": (w["label"], _weather_detail(w)),
            "models": (PREDICTED, _model_detail()),
        }
    )


def summary(db: Session) -> dict:
    return {
        "streams": streams(db),
        "weather": weather_summary(db),
        "notice": (
            "Weather is the only genuinely live input in this build. Everything "
            "else is simulated or derived, and is labelled as such."
        ),
    }
