"""Shared JSON shapes, so every endpoint describes a shipment the same way."""

from __future__ import annotations

from datetime import timezone

from sqlalchemy.orm import Session

from app.models import Alert, Machine, RiskAssessment, Shipment, Workflow
from app.services import explain, maintenance, risk_engine

DISCLAIMER = (
    "Simulated operational data, live weather. Sensor telemetry, traffic and "
    "demand are generated by this application's own models; weather comes from "
    "Open-Meteo when reachable and is labelled when it does not. Melt Index, "
    "spoilage probability and rupee figures are derived decision-support "
    "estimates, not guarantees."
)


def iso(value) -> str | None:
    """ISO-8601 with an explicit UTC offset.

    SQLite returns naive datetimes. Serialised bare, the browser reads them as
    LOCAL time, which put every timestamp on screen 5.5 hours out in India.
    Stored values are UTC, so a naive one is marked as such.
    """
    if value is None:
        return None
    if value.tzinfo is None:
        value = value.replace(tzinfo=timezone.utc)
    return value.isoformat()


# ---------------------------------------------------------------------------
# Shipments
# ---------------------------------------------------------------------------


def shipment_summary(shipment: Shipment) -> dict:
    route = risk_engine.selected_route(shipment)
    return {
        "id": shipment.id,
        "code": shipment.code,
        "product": shipment.product.name if shipment.product else None,
        "category": shipment.product.category if shipment.product else None,
        "origin_city": shipment.origin_city,
        "destination_city": shipment.destination_city,
        "shipment_value_inr": shipment.shipment_value_inr,
        "machine_id": shipment.machine_id,
        "machine_code": shipment.machine.code if shipment.machine else None,
        "machine_health": shipment.machine.health_score if shipment.machine else None,
        "remaining_shelf_life_hours": round(shipment.remaining_shelf_life_hours, 2),
        "minutes_outside_safe_range": round(shipment.minutes_outside_safe_range, 1),
        # LIVE simulated telemetry, integrated by the physics tick.
        "cargo_temperature_c": round(shipment.cargo_temperature_c, 2),
        "ambient_temperature_c": round(shipment.ambient_temperature_c, 2),
        "safe_transit_temp_c": (
            shipment.product.safe_transit_temp_c if shipment.product else None
        ),
        "cold_chain_breached": bool(
            shipment.product
            and shipment.cargo_temperature_c > shipment.product.safe_transit_temp_c
        ),
        "progress_fraction": round(shipment.progress_fraction, 3),
        "melt_index": round(shipment.melt_index),
        "melt_index_exact": round(shipment.melt_index, 2),
        "spoilage_probability": shipment.spoilage_probability,
        "expected_loss_inr": shipment.expected_loss_inr,
        "loss_avoided_inr": shipment.loss_avoided_inr,
        "status": shipment.status,
        "is_hero": shipment.is_hero,
        "current_route": route.label if route else None,
        "eta_minutes": (route.eta_minutes + route.delay_minutes) if route else None,
        "origin": {"lat": shipment.origin_lat, "lon": shipment.origin_lon},
        "destination": {"lat": shipment.dest_lat, "lon": shipment.dest_lon},
        "updated_at": iso(shipment.updated_at),
    }


def assessment_payload(assessment: RiskAssessment) -> dict:
    return {
        "id": assessment.id,
        "computed_at": iso(assessment.computed_at),
        "melt_index": round(assessment.melt_index, 2),
        "route_label": assessment.route_label,
        "components": {
            "temperature_risk": assessment.temperature_risk,
            "refrigeration_risk": assessment.refrigeration_risk,
            "traffic_risk": assessment.traffic_risk,
            "weather_risk": assessment.weather_risk,
            "shelf_life_risk": assessment.shelf_life_risk,
            "eta_risk": assessment.eta_risk,
        },
        "inputs": {
            "minutes_outside_safe_range": assessment.minutes_outside_safe_range,
            "cooling_efficiency_drop": assessment.cooling_efficiency_drop,
            "traffic_delay_minutes": assessment.traffic_delay_minutes,
            "remaining_shelf_life_hours": assessment.remaining_shelf_life_hours,
            "weather_level": assessment.weather_level,
            "machine_code": assessment.machine_code,
            "eta_margin_hours": assessment.eta_margin_hours,
        },
    }


def _thermal(db: Session, shipment: Shipment) -> dict | None:
    """The heat balance behind this shipment's temperature risk.

    Computed by the physics module, not here and not in the browser, so the
    explanation on screen is the same arithmetic the simulation ran.
    """
    from app.simulation import physics

    if shipment.product is None:
        return None
    route = risk_engine.selected_route(shipment)
    state = physics.environment(db)
    ambient_c, humidity_pct, _, source = physics.ambient_for_route(db, route, state)
    payload = physics.thermal_explanation(
        ambient_c=ambient_c,
        humidity_pct=humidity_pct,
        efficiency=physics.effective_efficiency(shipment, route),
        cargo_c=float(shipment.cargo_temperature_c),
        safe_max=float(shipment.product.safe_transit_temp_c),
    )
    payload["humidity_pct"] = round(humidity_pct, 1)
    payload["ambient_source"] = source
    return payload


def shipment_detail(db: Session, shipment: Shipment) -> dict:
    optimization = risk_engine.optimize(shipment)
    assessment = risk_engine.latest_assessment(db, shipment.id)
    # A shipment can have SEVERAL pending workflows at once — the reroute plus
    # the maintenance ticket for its reefer. The Approve Reroute button must
    # target the REROUTE one specifically, so they are surfaced separately
    # rather than as "the latest pending workflow".
    pending = (
        db.query(Workflow)
        .filter(
            Workflow.related_shipment_id == shipment.id,
            Workflow.status == "PENDING_APPROVAL",
        )
        .order_by(Workflow.id.desc())
        .all()
    )
    pending_reroute = next((w for w in pending if w.workflow_type == "REROUTE"), None)
    history = (
        db.query(RiskAssessment)
        .filter(RiskAssessment.shipment_id == shipment.id)
        .order_by(RiskAssessment.id.desc())
        .limit(20)
        .all()
    )

    payload = shipment_summary(shipment)
    payload.update(
        {
            "thermal": _thermal(db, shipment),
            "unit_shelf_life_hours": shipment.product.unit_shelf_life_hours
            if shipment.product
            else None,
            "routes": [e.to_payload() for e in optimization.evaluations],
            "current_route_evaluation": (
                optimization.current.to_payload() if optimization.current else None
            ),
            "recommended_route_evaluation": (
                optimization.recommended.to_payload() if optimization.recommended else None
            ),
            "potential_loss_avoided_inr": optimization.loss_avoided_inr,
            "no_safe_option": optimization.no_safe_option,
            "should_reroute": optimization.should_reroute,
            "recommendation_text": explain.explain_recommendation(shipment, optimization),
            "explanation": (
                explain.explain_risk(shipment, assessment) if assessment else None
            ),
            "risk_history": [
                {
                    "computed_at": iso(a.computed_at),
                    "melt_index": round(a.melt_index, 2),
                }
                for a in reversed(history)
            ],
            "pending_reroute_workflow": (
                workflow_payload(pending_reroute) if pending_reroute else None
            ),
            "related_pending_workflows": [workflow_payload(w) for w in pending],
            "disclaimer": DISCLAIMER,
        }
    )
    return payload


# ---------------------------------------------------------------------------
# Machines
# ---------------------------------------------------------------------------


def machine_summary(machine: Machine) -> dict:
    return {
        "id": machine.id,
        "code": machine.code,
        "type": machine.type,
        "type_label": machine.type.replace("_", " ").title(),
        "location": machine.location,
        "health_score": round(machine.health_score, 1),
        "cooling_efficiency": round(machine.cooling_efficiency, 1),
        "baseline_cooling_efficiency": round(machine.baseline_cooling_efficiency, 1),
        "degradation_rate_per_hour": round(machine.degradation_rate_per_hour, 3),
        "operating_hours": round(machine.operating_hours, 1),
        # Condition risk: the health-based rule that raises workflows.
        "failure_probability": machine.failure_probability,
        # Failure within 24h: the trend-based classifier (None if too few readings).
        "ml_failure_probability": maintenance.ml_failure_for(machine),
        "estimated_failure_hours": machine.estimated_failure_hours,
        "status": machine.status,
        "anomaly_score": machine.anomaly_score,
        "anomaly_detected": machine.anomaly_detected,
        "assigned_shipments": [s.code for s in machine.active_shipments],
        "updated_at": iso(machine.updated_at),
    }


def machine_detail(db: Session, machine: Machine, readings_limit: int = 40) -> dict:
    assessment = maintenance.assess(machine)
    readings = list(machine.readings)[-readings_limit:]
    payload = machine_summary(machine)
    payload.update(
        {
            "insufficient_data": assessment.insufficient_data,
            "ml_failure_probability": assessment.ml_failure_probability,
            "top_risk_factors": assessment.top_risk_factors,
            "explanation": explain.explain_machine(machine, assessment),
            "readings": [
                {
                    "timestamp": iso(r.timestamp),
                    "operating_hours": r.operating_hours,
                    "temperature": r.temperature,
                    "vibration": r.vibration,
                    "current": r.current,
                    "pressure": r.pressure,
                    "cooling_efficiency": r.cooling_efficiency,
                    "humidity": r.humidity,
                }
                for r in readings
            ],
            "open_workflows": [
                workflow_payload(w)
                for w in db.query(Workflow)
                .filter(
                    Workflow.related_machine_id == machine.id,
                    Workflow.status == "PENDING_APPROVAL",
                )
                .order_by(Workflow.id.desc())
                .all()
            ],
            "disclaimer": DISCLAIMER,
        }
    )
    return payload


# ---------------------------------------------------------------------------
# Workflows and alerts
# ---------------------------------------------------------------------------


def workflow_payload(workflow: Workflow) -> dict:
    return {
        "id": workflow.id,
        "workflow_type": workflow.workflow_type,
        "trigger_reason": workflow.trigger_reason,
        "related_shipment_id": workflow.related_shipment_id,
        "related_machine_id": workflow.related_machine_id,
        "confidence": workflow.confidence,
        "confidence_score": workflow.confidence_score,
        "impact_inr": workflow.impact_inr,
        "status": workflow.status,
        "recommendation_text": workflow.recommendation_text,
        "resolution_note": workflow.resolution_note,
        "proposed_route_id": workflow.proposed_route_id,
        "executed_route_id": workflow.executed_route_id,
        "created_at": iso(workflow.created_at),
        "resolved_at": iso(workflow.resolved_at),
        "requires_approval": workflow.status == "PENDING_APPROVAL",
        "simulated_execution": True,
    }


def alert_payload(alert: Alert) -> dict:
    return {
        "id": alert.id,
        "severity": alert.severity,
        "message": alert.message,
        "related_type": alert.related_type,
        "related_id": alert.related_id,
        "is_read": alert.is_read,
        "created_at": iso(alert.created_at),
    }
